version: "3.3"

services:
  webapp:
    image: ${DTR_URL}/demo/cidemo:${TAG}
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: continue
      labels:
        - "com.docker.ucp.mesh.http.80=internal_port=80,external_route=http://cidemo-${ENVIRONMENT}.${DOMAIN_NAME}"
        - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT}"
    networks:
      - cidemo
      - ucp-hrm

networks:
  cidemo:
    driver: overlay
    labels:
      - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT}"
  ucp-hrm:
    external: true
